### ISSUE TITLE
Remove `reflect-metadata` package

### ISSUE THREAD

**Issue by willpinha** [willpinha/realworld-node#17]

**Comment by Kingpin98k** [comment]
Hi, I am thinking of working on the issue.
Just wanted to ask if the application is using reflect-metadata internally, i.e. if removing it directly will cause any error?

**Comment by willpinha** [comment]
The `reflect-metadata` package was imported because the [TypeORM documentation](https://typeorm.io/#installation) says it should be imported.

Since the REST API was working without importing the package, I assumed it was possible to remove it.

Today I discovered that not using it can cause TypeORM bugs due to TypeScript decorators like `@Column()`. To prevent these bugs, the package will remain in the project, and will be imported. See [here](https://stackoverflow.com/questions/49618719/why-does-typeorm-need-reflect-metadata) for more information about `reflect-metadata`

This issue will be closed. Thank you for your contribution!
